### ISSUE TITLE
Support for Beagle on Jetpack Compose?

### ISSUE THREAD

**Issue by RyeGordo** [pandulapeter/beagle#97]
Can Beagle be integrated with apps in Jetpack Compose?

I see no current issues related to this.
And it's not fully clear after reviewing Issue #88 -- Jetpack Compose is not supported, but it seems to have worked for the developer who raised the issue.

If Jetpack Compose is not supported, will it be supported in the future?

**Comment by pandulapeter** [comment]
Hi!

The library should be working fine on top of Compose apps, I know about full Compose projects that use it without issues.

There is no difference in setup whatsoever: you just have to initialize it in your custom Application class.

Do let me know if you encounter any issues as right now I'm not aware of any Compose related problems.

**Comment by RyeGordo** [comment]
Hello again:

Yes, I do have an issue on Compose.
My implementation works when testing in fragments, but not in Compose -- for any UI type.

```groovy
beagleVersion = "2.6.6"
beagleUiType = "ui-drawer"
```
```groovy
debugImplementation "com.github.pandulapeter.beagle:$beagleUiType:$beagleVersion"
```
```kotlin
override fun onCreate() {
    super.onCreate()

    Beagle.initialize(this)

    Beagle.set(
        HeaderModule(
            title = getString(R.string.app_name),
            subtitle = BuildConfig.APPLICATION_ID,
            text = BuildConfig.VERSION_NAME
        ),
        PaddingModule(),
        TextModule("Rendering", TextModule.Type.SECTION_HEADER),
        KeylineOverlaySwitchModule(),
        AnimationDurationSwitchModule(),
        ScreenCaptureToolboxModule(),
        DividerModule(),
        ForceCrashButtonModule()
    )
}
```

**Comment by pandulapeter** [comment]
@RyeGordo That's weird...

Check out [this small project here](https://github.com/pandulapeter/wage-counter).

It's basically a blank canvas with Jetpack Compase + Beagle. [This last commit](https://github.com/pandulapeter/wage-counter/commit/7aacdb0b6d57851481e08f585264b835e7595273) added the debug menu, it's working fine on my devices. Maybe check it out but I suspect the problem lies somwhere else.

What exactly is the problem you see? The debug menu simply doesn't appear...? Are you sure that the custom Application class is registered in the Manifest? I can't think of any other issues right now.

**Comment by RyeGordo** [comment]
The problem I have is the Debug Drawer not appearing.
My Application class is registered in the manifest.

I made an attempt to re-implement with an Empty Compose project from Android Studio which still does not work.
The sample project you provided works. Aside from "dependency catalogs" and ".kts" which I am not using, I am trying to pick through the differences. I looked at pretty much everything from Themes to the gradle dependencies. 

I am unable to figure out what I'm doing wrong despite synchronizing the differences in both directions.

**Comment by pandulapeter** [comment]
I think I found the issue!

Bealge only injects itself into Activities that extend the `FragmentActivity` (`AppCompatActivity` is one such example).

If you create an "Empty Compose Activity", that's only going to extend` ComponentActivity` (which is one of the parent classes of `FragmentActivity`).

To fix your issue, simply make your Activity extend `AppCompatActivity`. Let me know if this works!

Sorry, I should have caught this earlier.

**Comment by RyeGordo** [comment]
Yes, it looks like `AppCompatActivity`.
I have Beagle finally working.

And no worries about missing this.  This is also something I should have suspected caught myself given that Beagle is still driven by Fragments/Activities.

Thanks, for your help.

**Comment by pandulapeter** [comment]
Glad we figured it out. You're right, Beagle uses an overlay Fragment to do its thing, so it needs the `supportFragmentManager` getter from `FragmentActivity`. I'll update the readme to highlight this fact.
